### ISSUE TITLE
Bar not properly alligned

### ISSUE THREAD

**Issue by WickedSchnitzel** [jayugg/BalancedThirst#2]
![Vintagestory Screenshot 2024 06 26 - 22 52 35 06](https://github.com/jayugg/BalancedThirst/assets/61825560/07131e07-60f6-4ddf-8041-279ce3d61dc0)

**Comment by WickedSchnitzel** [comment]
Changing GUI scale will move it around, but not properly align it as well.
v0.0.13

**Comment by jacopouggeri** [comment]
There is a client config option to add offset to align it, but now this should be fixed in v0.0.14, the bar will be automatically aligned with the hunger bar.
