### ISSUE TITLE
fix: `XSkillsCompat.ShouldLoad` and  throws NRE when called by other mods

### ISSUE THREAD

**Issue by ApacheTech** [jayugg/BalancedThirst#3]
You are using instanced fields within a static property call here:

https://github.com/jayugg/BalancedThirst/blob/master/BalancedThirst/Compatibility/XSkillsCompat.cs#L15

This throws a `NullReferenceException` when the method is called by a mod lower in the load order. In this case, my Gantry MDK tries to add loadable mod systems into its service collection.

One way to fix this would be to add a fallback to `BTCore`, when `_api` is null.

https://github.com/jayugg/BalancedThirst/blob/master/BalancedThirst/BTCore.cs#L26-L27

```csharp
    public static bool IsHoDLoaded => _api?.ModLoader.IsModEnabled("hydrateordiedrate") ?? false;
    public static bool IsXSkillsLoaded => _api?.ModLoader.IsModEnabled("xskills") ?? false;
```

But there may be a more robust solution you'd want to add into place.

I do wish there was a simple way to inject an API into the `ShouldLoad` method. It would solve a lot of these problems.

**Comment by jacopouggeri** [comment]
Thank you for the suggestion, what I’m doing is quite crude, but it was all I could think of when rushing to add compatibility at the time. Will definitely add a fallback, and think of a better way to detect when a mod has loaded.
