### ISSUE TITLE
Thrist not decrease

### ISSUE THREAD

**Issue by AdrienGearworker** [jayugg/BalancedThirst#6]
Hello, I think your mod is awesome but I have a problem: my thirst bar not deplete, always stay at 1500, i've tried changing parameters like thrist speed and use only this mod but nothing help, would you check that?

**Comment by jacopouggeri** [comment]
Is this on a fresh world? Does it happen if you start a new world? I cannot know what the issue is without more information. Are you sure you just haven't played enough? Thirst has a slight delay from when you start a world before it starts decreasing.

**Comment by AdrienGearworker** [comment]
I leave a world open for a while and wait and indeed, it works but there is anyway of eliminate the delay like the hydrate or diedrate? Because I really like your mod mechanics

**Comment by jacopouggeri** [comment]
Will not have this in the new version
